const styling = {
    COLOR_BRAND_PRIMARY: '#FB5758',

    COLOR_TEXT_DEFAULT: '#1E2126',
    COLOR_TEXT_LIGHTER: '#67696C',

    COLOR_BG_SUBTLE: '#F9F9F9',
    COLOR_BG_LIGHT: '#F1F1F1',
    COLOR_BG_LIGHT_PRIMARY: '#FEEDED',
    COLOR_BG_LIGHT_SECONDARY: '#E4F2F7',

    COLOR_BORDER_LIGHT: '#ECECEC',

    FONT_FAMILY_BRAND: 'ClearSans-Bold',
};

export {styling};
