const styling = {
    COLOR_BRAND_PRIMARY: '#FB5758',

    COLOR_TEXT_DEFAULT: '#1E2126',
    COLOR_TEXT_LIGHTER: '#777A7D',
    COLOR_TEXT_ERROR: '#DA3019',

    COLOR_BG_LIGHT: '#F1F1F1',
    COLOR_BG_LIGHT_PRIMARY: '#FEEDED',
    COLOR_BG_LIGHT_SECONDARY: '#E4F2F7',
    COLOR_BG_SUBTLE_SECONDARY: '#E4F2F760',

    COLOR_BORDER_LIGHTEST: '#F5F5F5',
    COLOR_BORDER_LIGHT: '#ECECEC',
    COLOR_BORDER_MEDIUM: '#ABABAB',

    FONT_FAMILY_BRAND: 'ClearSans-Bold',
};

export { styling };
